apiVersion: v1
kind: Namespace
metadata:
  name: sql-injection
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: sql-injection-service
  namespace: sql-injection
spec:
  ports:
    - name: http
      protocol: TCP
      port: 33003
      targetPort: http
  selector:
    app: sql-injection-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-injection-deployment
  namespace: sql-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-injection-app
  template:
    metadata:
      labels:
        app: sql-injection-app
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: sql-injection
          image: isolatedchallengesv4registry.azurecr.io/web/sql-injection
          ports:
            - name: http
              containerPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sql-injection-ingressroute
  namespace: sql-injection
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`sql-injection.isolated.trojanc.tf`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: sql-injection-service
      port: http
